### ISSUE TITLE
We need a personalisation icon 

### ISSUE THREAD

**Issue by tmsndrs** [LabD/wagtail-personalisation#101]
One icon that communicates personalisation in the navigation and explorer. 

The current icon is already used in multiple places around Wagtail CMS.

**Comment by tomdyson** [comment]
Several third party Wagtail apps use Font Awesome, and there's an existing wagtailfontawesome app which makes it easy to include, so it'll make things simpler if we can pick something from http://fontawesome.io/icons/ (how about http://fontawesome.io/icon/snowflake-o/ ?)

**Comment by jberghoef** [comment]
#118

**Comment by jberghoef** [comment]
Merged into master branch and fixed.
