### ISSUE TITLE
Sandbox creation error

### ISSUE THREAD

**Issue by tomdyson** [LabD/wagtail-personalisation#147]
```bash
mkvirtualenv dispose-wagx
git clone https://github.com/LabD/wagtail-personalisation.git
cd wagtail-personalisation
make sandbox
```

yields `django.core.exceptions.FieldDoesNotExist: HomePage has no field named 'canonical_page'`

**Comment by gasman** [comment]
Working for me on python3.6 - what version of python are you running?

**Comment by tomdyson** [comment]
Yes, working for me on Python 3.6. It fails on Python 2.7.

**Comment by mvantellingen** [comment]
Should be fixe in master
