### ISSUE TITLE
TemplateSyntaxError: 'admin_static' is not a registered tag library

### ISSUE THREAD

**Issue by bmoe872** [LabD/wagtail-personalisation#164]
# What the issue is
- Upon successful installation of the library (`pip install` and throwing it into installed_apps in the settings.py) I go to the admin, and when I click on 'segments' the above error appears.
- I am trying to install this within a preexisting wagtail setup.

# My setup:
Django==1.11.0
Wagtail==1.10.1
Using Jinja2 Templates, but I don't think that should affect the admin as that should still be rendered via django templates, and it hasn't caused any issues elsewhere, but I could be wrong.
Jinja2==2.9.5

Please let me know if there is any other pertinent information you would like. 

Full Stack trace:
```
django.template.exceptions.TemplateSyntaxError: 'admin_static' is not a registered tag library. Must be one of:
absolute
absolute_future
cache
compress
easy_thumbnails_tags
gravatar
highlighting
i18n
indent_text
l10n
modeladmin_tags
static
staticfiles
syntax_color
thumbnail
truncate_letters
tz
wagtail_personalisation_filters
wagtail_personalisation_tags
wagtail_thumbnail
wagtailadmin_tags
wagtailcore_tags
wagtailembeds_tags
wagtailimages_tags
wagtailmetadata_tags
wagtailuserbar
wagtailusers_tags
widont
```

**Comment by blurrah** [comment]
Taking a small guess here, you seem to be missing the `admin_static` templatetag which is part of the `django.contrib.admin` app. Could you double check your settings file if you've added that app?

You can check the settings file in our sandbox Django app to see if you're missing something else that might give the problems.

**Comment by bmoe872** [comment]
@blurrah thanks for the reply, that was definitely the issue! Now I've also noticed my urls.py is different from what you guys have, and what wagtail had suggested, so I'll have to move that around too!

**Comment by blurrah** [comment]
Good to hear that fixed it. Have fun with Wagtail Personalisation!
