### ISSUE TITLE
Variants break the reordering in wagtail admin.

### ISSUE THREAD

**Issue by bmoe872** [LabD/wagtail-personalisation#168]
# What the issue is
After we create a new variant, clicking the little order icon in the top left brings up the error:
`AttributeError: 'Page' object has no attribute 'personalisation_metadata'`

This happens at the root level of the explorer when trying to reorder the pages.

# More details
Django == 1.11.0
wagtail == 1.10.1
wagtail-personalisation == 0.9.0
Jinja2==2.9.5 - I don't think this would have anything to do with it though.

**Comment by jberghoef** [comment]
Fixed in #165
