### ISSUE TITLE
Segment.DoesNotExist raised in SessionSegmentsAdapter

### ISSUE THREAD

**Issue by tm-kn** [LabD/wagtail-personalisation#46]
I had `Segment.DoesNotExist` raised on this [line](https://github.com/LabD/wagtail-personalisation/blob/7b01913d3263b8d25b8f34e4d03d87bd2a927395/src/personalisation/adapters.py#L98) but I cannot reproduce it now. Clearing out the user sessions helped. It affected only one session after some of the segments were deleted by another user.

**Comment by jberghoef** [comment]
Fixed with #bffd13d, closing.
