### ISSUE TITLE
Write a blog post with information about the project

### ISSUE THREAD

**Issue by mvantellingen** [LabD/wagtail-personalisation#53]

**Comment by pimvernooij** [comment]
I'll be working on:

- [ ] write blog post [IN PROGRESS]
- [ ] publish blog on https://blog.labdigital.nl
- [ ] post blog on https://wagtail.io/blog/

I'd like some reviews before publishing :)

**Comment by tomdyson** [comment]
I'm happy to review! Do you have any photos? I can take some of the team here.

**Comment by pimvernooij** [comment]
Good idea! We'll take some, and can add a short gallery to the post.

**Comment by tomdyson** [comment]
Here are some. Maybe we could get some in reverse (LabD in the foreground, Torchbox on screen).

![p1030782](https://cloud.githubusercontent.com/assets/15543/26627389/3c89b82e-45f2-11e7-9c4f-64f903d7df14.jpg)
![p1030784](https://cloud.githubusercontent.com/assets/15543/26627392/3ca7dc6e-45f2-11e7-89c2-c5a025abba21.jpg)
![p1030785](https://cloud.githubusercontent.com/assets/15543/26627391/3ca48906-45f2-11e7-8340-97e41578bf99.jpg)
![p1030786](https://cloud.githubusercontent.com/assets/15543/26627393/3caa271c-45f2-11e7-8c39-d8b99034fb3b.jpg)

**Comment by pimvernooij** [comment]
Social message could be:

Today, Lab Digital and Torchbox organised a short sprint with one goal: introducing Wagtail Personalisation support to the open source community. In one day we finalised the module and released version 1.0, suitable for production-usage.

Read more about it on our blog! [link]
