### ISSUE TITLE
Create a PersonalizableMixin class 

### ISSUE THREAD

**Issue by mvantellingen** [LabD/wagtail-personalisation#72]
Instead of subclass the current PersonalizablePage class it should be moved to a mixin

**Comment by gasman** [comment]
I think that having a base PersonalizablePage class might be unavoidable. We need somewhere in the database to put the `canonical_page` / `segment` / `is_segmented` model fields, and if there isn't a dedicated table in the multi-table-inheritance hierarchy for those, then the only alternative is to use `abstract = True` and have them defined separately on each specific page type. This then makes it impossible to run queries across all page types (e.g. "find all pages that have personalisation for segment X").

**Comment by robmoorman** [comment]
When this is fixed, we should also not be able to add a PersonalisablePage while adding new pages in the tree

<img width="577" alt="screen shot 2017-05-31 at 11 50 57" src="https://cloud.githubusercontent.com/assets/529396/26626461/9789a7ca-45f7-11e7-9d1d-579bffb895f4.png">

**Comment by gasman** [comment]
@robmoorman Just fixed in #104 :-)
